### ISSUE TITLE
Long passwords seem to get truncated

### ISSUE THREAD

**Issue by hsjunn** [ts1/BLEUnlock#19] opened 2020-10-15 02:34 UTC
It seems passwords are remembered up to 20 characters only. When my password was longer than that the app kept failing to log me in; it succeeded only after I had shortened mine.

If it's a design decision, I think you need to at least specify that in the readme.

**Comment by ts1** [comment] 2020-10-15 02:46
Thanks for the report @hsjunn!
That is not the intended behavior. I will try to find out what is truncating the password.

**Comment by ts1** [comment] 2020-10-15 03:18
This will be fixed in next release.

**Closed** 2020-10-17 04:34 UTC
